- hosts: uat
  remote_user: ec2-user
  become: yes
  tasks:
    - name: copying file with playbook
      copy:
        src: /home/ec2-user/Fc2_repo/test.sh
        dest: /home/ec2-user/
        mode: '777'
    - name: Run shell script
      command: sh /home/ec2-user/test.sh
